name: "Setup Node.js with Zmicro"
description: "github action for setuping docker (+buildx) with Zmicro"
author: "Zero <GitHub: whatwewant>"
branding:
  icon: "message-square"
  color: "green"
inputs:
  always-auth:
    description: "Set always-auth in npmrc."
    default: "false"
  node-version:
    required: false
    description: specify nodejs version
    default: "v16"
  registry-url:
    description: "Optional registry to set up for auth. Will set the registry in a project level .npmrc and .yarnrc file, and set up auth to read in from env.NODE_AUTH_TOKEN."
  token:
    description: Used to pull node distributions from node-versions. Since there's a default, this is typically not supplied by the user. When running this action on github.com, the default value is sufficient. When running on GHES, you can pass a personal access token for github.com if you are experiencing rate limiting.
    default: ${{ github.server_url == 'https://github.com' && github.token || '' }}

outputs:
  node-version:
    description: 'The installed node version.'
    value: ${{ steps.node.outputs.node-version }}
  npm-version:
    description: 'The installed npm version.'
    value: ${{ steps.node.outputs.npm-version }}
  yarn-version:
    description: 'The installed yarn version.'
    value: ${{ steps.node.outputs.yarn-version }}
  pnpm-version:
    description: 'The installed pnpm version.'
    value: ${{ steps.node.outputs.pnpm-version }}
  cnpm-version:
    description: 'The installed cnpm version.'
    value: ${{ steps.node.outputs.cnpm-version }}


runs:
  using: composite
  steps:
    - name: Setup Zmicro
      uses: zmicro-design/action-setup-zmicro@v1

    - name: Install Zmicro Setup Plugin
      shell: bash
      run: zmicro plugin install setup

    - name: Setup Node.js
      shell: bash
      id: node
      run: |
        export NODE_VERSION=${{ inputs.node-version }}
        export NPM_TOKEN=${{ inputs.token }}
        export REGISTRY=${{ inputs.registry-url }}
        export ALWAYS_WAYS_AUTH=${{ inputs.always-auth }}

        zmicro setup github-actions node
