name: Test

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x, 18.x]
    steps:
      - uses: actions/checkout@v2

      - name: Build on Node.js ${{ matrix.node-version }}
        uses: ./
        id: node
        with:
          node-version: ${{ matrix.node-version }}

      - name: Show Info From Output
        run: |
          echo "NVM ${{ steps.node.outputs.nvm-version }}"
          echo "Node.js ${{ steps.node.outputs.node-version }}"
          echo "NPM ${{ steps.node.outputs.npm-version }}"
          echo "Yarn ${{ steps.node.outputs.yarn-version }}"
          echo "Pnpm ${{ steps.node.outputs.pnpm-version }}"

      - name: Show Info by Command
        shell: zmicro {0}
        run: |
          echo "NVM $(nvm version)"
          echo "Node.js $(node --version)"
          echo "NPM $(npm --version)"
          echo "Yarn $(yarn --version)"

          # pnpm only works on node >= 16.14
          if [ "$(semver::compare_gte $NODE_VERSION v16.14)" = "true" ]; then
            echo "Pnpm $(pnpm --version)"
          fi

